In [2]:
!uv pip show pandas
!uv pip show numpy

Using Python 3.12.9 environment at: /Users/gustavomontenegro/Documents/pro-certs/fast-api/.venv
Name: pandas
Version: 3.0.1
Location: /Users/gustavomontenegro/Documents/pro-certs/fast-api/.venv/lib/python3.12/site-packages
Requires: numpy, python-dateutil
Required-by: fast-api
Using Python 3.12.9 environment at: /Users/gustavomontenegro/Documents/pro-certs/fast-api/.venv
Name: numpy
Version: 2.4.2
Location: /Users/gustavomontenegro/Documents/pro-certs/fast-api/.venv/lib/python3.12/site-packages
Requires:
Required-by: pandas

#### GroupBy

In [3]:
import pandas as pd
import numpy as np

# 1. Creamos el dataset de ejemplo
data = {
    'Vendedor': ['Ana', 'Ana', 'Ana', 'Beto', 'Beto', 'Carlos', 'Carlos'],
    'Monto_Venta': [100, 150, 600, 200, 250, 300, 350]
}

data

{'Vendedor': ['Ana', 'Ana', 'Ana', 'Beto', 'Beto', 'Carlos', 'Carlos'],
 'Monto_Venta': [100, 150, 600, 200, 250, 300, 350]}

In [4]:
data.keys()

dict_keys(['Vendedor', 'Monto_Venta'])

In [5]:
df = pd.DataFrame(data)

# --- DIFERENCIA 1: .mean() (Agregación) ---
# Esto reduce el dataset. Útil para un resumen rápido.
resumen_promedios = df.groupby('Vendedor')['Monto_Venta'].mean()

print("--- RESULTADO DE .mean() ---")
print(resumen_promedios)
print(f"Tamaño del resultado: {len(resumen_promedios)}")

--- RESULTADO DE .mean() ---
Vendedor
Ana       283.333333
Beto      225.000000
Carlos    325.000000
Name: Monto_Venta, dtype: float64
Tamaño del resultado: 3

In [6]:
# --- DIFERENCIA 2: .transform('mean') (Transformación) ---
# Esto mantiene el tamaño original. Útil para Feature Engineering.
df['Promedio_Vendedor'] = df.groupby('Vendedor')['Monto_Venta'].transform('mean')

print("--- RESULTADO DE .transform() ---")
print(df)
print(f"Tamaño del resultado: {len(df)} filas")

--- RESULTADO DE .transform() ---
  Vendedor  Monto_Venta  Promedio_Vendedor
0      Ana          100         283.333333
1      Ana          150         283.333333
2      Ana          600         283.333333
3     Beto          200         225.000000
4     Beto          250         225.000000
5   Carlos          300         325.000000
6   Carlos          350         325.000000
Tamaño del resultado: 7 filas

In [ ]:
df.groupby('Vendedor')['Monto_Venta'] #Es un lazzy object, pandas ya sabe cómo va a agrupar los datos, pero no hace ningún cálculo hasta que le pidas una función final.

#### Apply

In [8]:
data_apply = {
    "Ticket_ID": ["T1","T2","T3"],
    "Impacto": ["Alto", "Bajo", "Alto"],
    "Horas": [15,20,5]
}

df_tickets = pd.DataFrame(data_apply)

df_tickets

  Ticket_ID Impacto  Horas
0        T1    Alto     15
1        T2    Bajo     20
2        T3    Alto      5

In [9]:
# Definimos una función con nuestra lógica de negocio
def categorizar_urgencia(fila):
    if fila['Impacto'] == 'Alto' and fila['Horas'] > 10:
        return 'Crítico'
    else:
        return 'Normal'

# Aplicamos la función a lo largo de las columnas (axis=1)
df_tickets['Prioridad'] = df_tickets.apply(categorizar_urgencia, axis=1)

# Resultado:
# T1 -> Crítico (Alto + 15)
# T2 -> Normal  (Bajo + 20)
# T3 -> Normal  (Alto + 5)

df_tickets

  Ticket_ID Impacto  Horas Prioridad
0        T1    Alto     15   Crítico
1        T2    Bajo     20    Normal
2        T3    Alto      5    Normal

#### Merge

In [12]:
data_merge_oportunidades = {
    "Opp_ID":["501","502"],
    "Monto":[1000,2000],
    "Lead_ID":["1","2"]
}

data_merge_clientes = {
    "Lead_ID":["1","2"],
    "Empresa":["Apple","Google"]
}

df_oportunidades = pd.DataFrame(data_merge_oportunidades)
print(df_oportunidades)
df_clientes = pd.DataFrame(data_merge_clientes)
print(df_clientes)

df_final_merge = df_oportunidades.merge(df_clientes, on = "Lead_ID", how = "left")
df_final_merge

  Opp_ID  Monto Lead_ID
0    501   1000       1
1    502   2000       2
  Lead_ID Empresa
0       1   Apple
1       2  Google

  Opp_ID  Monto Lead_ID Empresa
0    501   1000       1   Apple
1    502   2000       2  Google

In [13]:
data_pivot = {
    "Cliente":["Apple","Apple", "Google"],
    "Año":[2023,2024,2023],
    "Venta":[500,700,400]
}

df_anual = pd.DataFrame(data_pivot)
df_anual

  Cliente   Año  Venta
0   Apple  2023    500
1   Apple  2024    700
2  Google  2023    400

#### Pivot

In [14]:
df_pivot = df_anual.pivot(index = "Cliente", columns = "Año", values= "Venta")
df_pivot

Año       2023   2024
Cliente
Apple    500.0  700.0
Google   400.0    NaN

In [22]:
df_pivot[0:1]

Año       2023   2024
Cliente
Apple    500.0  700.0

#### Melt

In [23]:
data_melt = {
    "Producto":["iPhone","Pixel"],
    "Enero":[100,80],
    "Febrero":[120,90]
}

df_meses = pd.DataFrame(data_melt)
df_meses

  Producto  Enero  Febrero
0   iPhone    100      120
1    Pixel     80       90

In [24]:
df_limpio = pd.melt(df_meses, id_vars = ["Producto"], var_name = "Mes", value_name="Cantidad")
df_limpio

  Producto      Mes  Cantidad
0   iPhone    Enero       100
1    Pixel    Enero        80
2   iPhone  Febrero       120
3    Pixel  Febrero        90

#### Ejercicio

Reto Final de Pandas:

- Merge: Une df_ventas_sf con df_vendedor para que cada venta tenga el nombre y el país.

- Transform: Crea una columna Total_Vendedor que sume las ventas de cada persona.

- Filtrado: Quédate solo con las filas de los vendedores cuyo Pais sea "MX".

¿Te animas a escribir el código para el punto 1 y 2? Si lo logras, habrás demostrado que puedes navegar por múltiples tablas y generar métricas grupales, ¡exactamente lo que un ML Engineer hace todo el día!

In [26]:
data_vendedor = {
    "ID":["A1", "B2"],
    "Nombre":["Juan", "Ana"],
    "Pais":["MX", "US"]
}

data_ventas_sf = {
    "ID":["A1", "A1", "B2"],
    "Producto":["Einstein", "Tableau", "Slack"],
    "Monto":[1000, 500, 2000]
}

df_vendedor = pd.DataFrame(data_vendedor)
print(df_vendedor)

df_ventas_sf = pd.DataFrame(data_ventas_sf)
print(df_ventas_sf)

   ID Nombre Pais
0  A1   Juan   MX
1  B2    Ana   US
   ID  Producto  Monto
0  A1  Einstein   1000
1  A1   Tableau    500
2  B2     Slack   2000

In [ ]:
# Merge | Ventas por vendedor

df_ventas_por_vendedor = df_ventas_sf.merge(df_vendedor, on = "ID", how = "left")
df_ventas_por_vendedor

   ID  Producto  Monto Nombre Pais
0  A1  Einstein   1000   Juan   MX
1  A1   Tableau    500   Juan   MX
2  B2     Slack   2000    Ana   US

In [31]:
# Transform | Suma de ventas por cada persona

df_ventas_por_vendedor["ventas_total"] = df_ventas_por_vendedor.groupby("Nombre")["Monto"].transform("sum")
df_ventas_por_vendedor

   ID  Producto  Monto Nombre Pais  ventas_total
0  A1  Einstein   1000   Juan   MX          1500
1  A1   Tableau    500   Juan   MX          1500
2  B2     Slack   2000    Ana   US          2000

In [ ]:
# Filtrado por país

df_ventas_por_vendedor_mx = df_ventas_por_vendedor[df_ventas_por_vendedor["Pais"] == "MX"]
df_ventas_por_vendedor_mx

   ID  Producto  Monto Nombre Pais  ventas_total
0  A1  Einstein   1000   Juan   MX          1500
1  A1   Tableau    500   Juan   MX          1500

#### Respuesta

In [36]:
data_vendedor = {
    "ID":["A1", "B2"],
    "Nombre":["Juan", "Ana"],
    "Pais":["MX", "US"]
}

data_ventas_sf = {
    "ID":["A1", "A1", "B2"],
    "Producto":["Einstein", "Tableau", "Slack"],
    "Monto":[1000, 500, 2000]
}

# 0. Crear dataframes
df_vendedor = pd.DataFrame(data_vendedor)
df_ventas_sf = pd.DataFrame(data_ventas_sf)

# 1. Merge | Ventas por vendedor
df_ventas_por_vendedor = df_ventas_sf.merge(df_vendedor, on = "ID", how = "left")

# 2. Transform | Suma de ventas por cada persona
df_ventas_por_vendedor["ventas_total"] = df_ventas_por_vendedor.groupby("ID")["Monto"].transform("sum")
# Aunque esta parte es correcta, es siempre mejor agrupar por ID, debido a que son identificadores únicos

# 3. Filtrado por país
df_ventas_por_vendedor_mx = df_ventas_por_vendedor[df_ventas_por_vendedor["Pais"] == "MX"]

In [37]:
df_ventas_por_vendedor_mx

   ID  Producto  Monto Nombre Pais  ventas_total
0  A1  Einstein   1000   Juan   MX          1500
1  A1   Tableau    500   Juan   MX          1500

Te dan un DataFrame con 10 millones de filas. Tiene las columnas Prioridad (que solo puede ser 'Alta', 'Media', 'Baja') y Monto.

- ¿Qué comando usarías para ver cuánto espacio ocupa este DataFrame en RAM?

- ¿Cómo optimizarías la columna Prioridad?

- Tienes que sumarle el 10% de impuestos a todos los montos. Escribe la línea de código más rápida para hacerlo.

In [38]:
df_ventas_por_vendedor_mx["ventas_total"] = df_ventas_por_vendedor_mx["ventas_total"] * 1.1
df_ventas_por_vendedor_mx

   ID  Producto  Monto Nombre Pais  ventas_total
0  A1  Einstein   1000   Juan   MX        1650.0
1  A1   Tableau    500   Juan   MX        1650.0

In [40]:
df_ventas_por_vendedor_mx.info(memory_usage="deep")

<class 'pandas.DataFrame'>
RangeIndex: 2 entries, 0 to 1
Data columns (total 6 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   ID            2 non-null      str
 1   Producto      2 non-null      str
 2   Monto         2 non-null      int64
 3   Nombre        2 non-null      str
 4   Pais          2 non-null      str
 5   ventas_total  2 non-null      float64
dtypes: float64(1), int64(1), str(4)
memory usage: 587.0 bytes

In [41]:
df_ventas_por_vendedor_mx.memory_usage(deep=True)

Index           132
ID              102
Producto        113
Monto            16
Nombre          106
Pais            102
ventas_total     16
dtype: int64

In [ ]:
df_ventas_por_vendedor_mx["Producto"] = df_ventas_por_vendedor_mx["Producto"].astype("category")
df_ventas_por_vendedor_mx["Pais"] = df_ventas_por_vendedor_mx["Pais"].astype("category")
df_ventas_por_vendedor_mx["Monto"] = df_ventas_por_vendedor_mx["Monto"].astype("int32")
df_ventas_por_vendedor_mx["ventas_total"] = df_ventas_por_vendedor_mx["ventas_total"].astype("float32")

In [43]:
df_ventas_por_vendedor_mx.info(memory_usage="deep")

<class 'pandas.DataFrame'>
RangeIndex: 2 entries, 0 to 1
Data columns (total 6 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   ID            2 non-null      str
 1   Producto      2 non-null      category
 2   Monto         2 non-null      int32
 3   Nombre        2 non-null      str
 4   Pais          2 non-null      category
 5   ventas_total  2 non-null      float32
dtypes: category(2), float32(1), int32(1), str(2)
memory usage: 524.0 bytes

In [44]:
df_ventas_por_vendedor_mx.memory_usage(deep=True)

Index           132
ID              102
Producto        115
Monto             8
Nombre          106
Pais             53
ventas_total      8
dtype: int64

In [50]:
def myfunc(n):
  return len(n)

x = map(myfunc, ('apple', 'banana', 'cherry'))
list(x)

[5, 6, 6]

In [81]:
def myfunc_b(n):
  return len(n)

list_b = ['apple', 'banana', 'cherry']

map_object = map(myfunc_b, list_b)
print(map_object)
result_list = list(map_object) #The iterable object gets exhausted the first time that it is converted to a list. 
# Iterators are single-use objects.
print(result_list)

<map object at 0x10ce156c0>
[5, 6, 6]

In [82]:
data_map = {
    "fruit": list_b,
    "len": result_list
}

df_map = pd.DataFrame(data_map)
df_map

    fruit  len
0   apple    5
1  banana    6
2  cherry    6

In [83]:
fruit_dic = {
    "banana" : "large banana",
    "apple" : "golden apple",
}

df_map["fruit"].map(fruit_dic)

0    golden apple
1    large banana
2             NaN
Name: fruit, dtype: str

In [85]:
df_map["fruit"].replace(fruit_dic)

0    golden apple
1    large banana
2          cherry
Name: fruit, dtype: str

In [86]:
df_map

    fruit  len
0   apple    5
1  banana    6
2  cherry    6

In [89]:
def sum(a):
    return a * 10

z = map(sum, df_map['len'])
df_map["len"] = list(z)

df_map

    fruit  len
0   apple   50
1  banana   60
2  cherry   60

Ejercicio de Claridad Total

Imagina este DataFrame `df_clientes`:

```

Nombre  Edad  Compras_Anuales
Juan     25       10
Ana      40       50

```

- Misión : 
  - Usa `map()` para crear una columna `Nombre_Mayus` (solo transforma el nombre).
  - Usa `apply()` con axis=1 para crear una columna Segmento:Si Edad > 30 Y Compras_Anuales > 20 -> 'Premium'De lo contrario -> 'Regular'

In [90]:
data_claridad_total = {
    "Nombre": ["Juan", "Ana"],
    "Edad": [25, 40],
    "Compras_Anuales": [10, 50]
}

df_cl = pd.DataFrame(data_claridad_total)
print(df_cl)
print(df_cl.info(memory_usage="deep"))
print(df_cl.memory_usage(deep=True))

  Nombre  Edad  Compras_Anuales
0   Juan    25               10
1    Ana    40               50
<class 'pandas.DataFrame'>
RangeIndex: 2 entries, 0 to 1
Data columns (total 3 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Nombre           2 non-null      str
 1   Edad             2 non-null      int64
 2   Compras_Anuales  2 non-null      int64
dtypes: int64(2), str(1)
memory usage: 269.0 bytes
None
Index              132
Nombre             105
Edad                16
Compras_Anuales     16
dtype: int64

In [91]:
df_cl["Nombre_Mayus"] = df_cl["Nombre"].map(lambda x:x.upper())
df_cl

  Nombre  Edad  Compras_Anuales Nombre_Mayus
0   Juan    25               10         JUAN
1    Ana    40               50          ANA

In [ ]:
def definir_segmento(row):
    if row["Edad"] > 30 and row["Compras_Anuales"] > 20:
        # row["Segmento"] = "Premium" | Esta asignación no es requerida.
        return "Premium"
    
    else:
        # row["Segmento"] = "Regular" | Esta asignación no es requerida
        return "Regular"
    

df_cl["Segmento"] = df_cl.apply(definir_segmento, axis = 1)

df_cl

  Nombre  Edad  Compras_Anuales Nombre_Mayus Segmento
0   Juan    25               10         JUAN  Regular
1    Ana    40               50          ANA  Premium